kind: pipeline
name: default

steps:
- name: openssl
  image: v7lin/openssl:1.1.1b
  environment:
    ENC_METHOD:
      from_secret: ENC_METHOD
    ENC_PASSWORD:
      from_secret: ENC_PASSWORD
  commands:
  - openssl enc -d -$ENC_METHOD -k $ENC_PASSWORD -in credentials.json.enc -out credentials.json
